"""
OmniPipe — Nuke menu.py
═══════════════════════════════════════════════════════════════════════
This file is auto-installed into Nuke's plugin path by the
install_nuke_hook.py script or by the workstation installer.

When Nuke boots, it scans all directories in NUKE_PATH for menu.py
files and executes them. This is Nuke's official plugin entry point.

DO NOT EDIT THIS FILE DIRECTLY — it is generated/overwritten by OmniPipe.
═══════════════════════════════════════════════════════════════════════
"""

import os
import sys

def _bootstrap_omnipipe():
    """Initialize OmniPipe inside Nuke."""
    repo_root = os.getenv("OMNIPIPE_REPO_ROOT", "")

    if not repo_root:
        # Auto-detect: walk sys.path for omnipipe package
        for p in sys.path:
            candidate = os.path.join(p, "omnipipe", "dcc", "nuke", "startup.py")
            if os.path.isfile(candidate):
                repo_root = os.path.dirname(os.path.dirname(
                    os.path.dirname(os.path.dirname(candidate))
                ))
                break

    if repo_root and repo_root not in sys.path:
        sys.path.insert(0, repo_root)
        vendor = os.path.join(repo_root, "omnipipe", "vendor")
        if os.path.isdir(vendor):
            sys.path.insert(0, vendor)

    try:
        from omnipipe.dcc.nuke.startup import bootstrap
        bootstrap()
    except ImportError as e:
        print(f"[OmniPipe] ERROR: Could not import startup module: {e}")
        print(f"[OmniPipe] Make sure OMNIPIPE_REPO_ROOT is set or the repo is in NUKE_PATH.")
    except Exception as e:
        print(f"[OmniPipe] ERROR during startup: {e}")
        import traceback
        traceback.print_exc()


# ── Execute ───────────────────────────────────────────────────────────────────
_bootstrap_omnipipe()
