site_name: OmniPipe Documentation
site_url: https://kamal-suryavanshi.github.io/OmniPipe/
site_description: A dynamic CG Studio Pipeline
theme: readthedocs

nav:
  - Home: index.md
  - Guides:
    - 1. Technical Director (TD) Guide: guides/td_guide.md
    - 2. QA & Tester Guide: guides/testing_guide.md
    - 3. Pipeline Developer Guide: guides/developer_guide.md
    - 4. Artist Usage Guide: guides/artist_guide.md
