site_name: OmniPipe Documentation
site_description: A dynamic CG Studio Pipeline
theme: readthedocs

nav:
  - Home: index.md
  - CLI Cheatsheet (Usage): cheatsheet.md
  - Master Test Plan: test_plan.md
  - Architecture Walkthroughs:
    - Task 1 & 2 (Repo & Context): walkthroughs/task_1_2.md
    - Task 3 (Path Manager): walkthroughs/task_3.md
    - Task 4 (Publish Design): walkthroughs/task_4.md
    - Task 5 (Validators): walkthroughs/task_5.md
    - Task 6 (Extractors): walkthroughs/task_6.md
