"""
OmniPipe — Maya userSetup.py
═══════════════════════════════════════════════════════════════════════
This file is auto-installed into Maya's scripts directory by the
install_maya_hook.py script or by the workstation installer.

When Maya boots, it executes this file. We use cmds.evalDeferred()
to ensure the full UI is loaded before touching shelves or dialogs.

DO NOT EDIT THIS FILE DIRECTLY — it is generated/overwritten by OmniPipe.
═══════════════════════════════════════════════════════════════════════
"""

import os
import sys

def _omnipipe_deferred_startup():
    """Runs after Maya UI is fully loaded."""
    # Resolve repo root from this file's expected install location
    # OR from an environment variable set by the install script
    repo_root = os.getenv("OMNIPIPE_REPO_ROOT", "")

    if not repo_root:
        # Fallback: try to find it relative to common install locations
        # E.g. userSetup.py lives in ~/maya/2025/scripts/ but repo is elsewhere
        print("[OmniPipe] Warning: OMNIPIPE_REPO_ROOT not set. "
              "Attempting auto-detection from sys.path…")
        for p in sys.path:
            candidate = os.path.join(p, "omnipipe", "dcc", "maya", "startup.py")
            if os.path.isfile(candidate):
                repo_root = os.path.dirname(os.path.dirname(
                    os.path.dirname(os.path.dirname(candidate))
                ))
                break

    if repo_root and repo_root not in sys.path:
        sys.path.insert(0, repo_root)
        vendor = os.path.join(repo_root, "omnipipe", "vendor")
        if os.path.isdir(vendor):
            sys.path.insert(0, vendor)

    try:
        from omnipipe.dcc.maya.startup import bootstrap
        bootstrap()
    except ImportError as e:
        print(f"[OmniPipe] ERROR: Could not import startup module: {e}")
        print(f"[OmniPipe] Make sure OMNIPIPE_REPO_ROOT is set or the repo is in PYTHONPATH.")
    except Exception as e:
        print(f"[OmniPipe] ERROR during startup: {e}")
        import traceback
        traceback.print_exc()


# ── Execute after Maya UI is ready ────────────────────────────────────────────
try:
    import maya.cmds as cmds
    cmds.evalDeferred("_omnipipe_deferred_startup()", lowestPriority=True)
    print("[OmniPipe] Deferred startup registered — will run after UI loads.")
except ImportError:
    # Not running inside Maya — skip (prevents crash during testing)
    pass
